/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as InternacoesRouteImport } from './routes/internacoes'
import { Route as PequenasCirurgiasRouteImport } from './routes/pequenas-cirurgias'
import { Route as ProducaoHospitalarRouteImport } from './routes/producao-hospitalar'
import { Route as FinanceiroFarmaciaRouteImport } from './routes/financeiro.farmacia'
import { Route as FinanceiroFeiraRouteImport } from './routes/financeiro.feira'
import { Route as FinanceiroLaboratorioRouteImport } from './routes/financeiro.laboratorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const InternacoesRoute = InternacoesRouteImport.update({
  id: '/internacoes',
  path: '/internacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PequenasCirurgiasRoute = PequenasCirurgiasRouteImport.update({
  id: '/pequenas-cirurgias',
  path: '/pequenas-cirurgias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoHospitalarRoute = ProducaoHospitalarRouteImport.update({
  id: '/producao-hospitalar',
  path: '/producao-hospitalar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroFarmaciaRoute = FinanceiroFarmaciaRouteImport.update({
  id: '/farmacia',
  path: '/farmacia',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFeiraRoute = FinanceiroFeiraRouteImport.update({
  id: '/feira',
  path: '/feira',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroLaboratorioRoute = FinanceiroLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/internacoes': typeof InternacoesRoute
  '/pequenas-cirurgias': typeof PequenasCirurgiasRoute
  '/producao-hospitalar': typeof ProducaoHospitalarRoute
  '/financeiro/farmacia': typeof FinanceiroFarmaciaRoute
  '/financeiro/feira': typeof FinanceiroFeiraRoute
  '/financeiro/laboratorio': typeof FinanceiroLaboratorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/internacoes': typeof InternacoesRoute
  '/pequenas-cirurgias': typeof PequenasCirurgiasRoute
  '/producao-hospitalar': typeof ProducaoHospitalarRoute
  '/financeiro/farmacia': typeof FinanceiroFarmaciaRoute
  '/financeiro/feira': typeof FinanceiroFeiraRoute
  '/financeiro/laboratorio': typeof FinanceiroLaboratorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/internacoes': typeof InternacoesRoute
  '/pequenas-cirurgias': typeof PequenasCirurgiasRoute
  '/producao-hospitalar': typeof ProducaoHospitalarRoute
  '/financeiro/farmacia': typeof FinanceiroFarmaciaRoute
  '/financeiro/feira': typeof FinanceiroFeiraRoute
  '/financeiro/laboratorio': typeof FinanceiroLaboratorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/internacoes'
    | '/pequenas-cirurgias'
    | '/producao-hospitalar'
    | '/financeiro/farmacia'
    | '/financeiro/feira'
    | '/financeiro/laboratorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/internacoes'
    | '/pequenas-cirurgias'
    | '/producao-hospitalar'
    | '/financeiro/farmacia'
    | '/financeiro/feira'
    | '/financeiro/laboratorio'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/financeiro'
    | '/internacoes'
    | '/pequenas-cirurgias'
    | '/producao-hospitalar'
    | '/financeiro/farmacia'
    | '/financeiro/feira'
    | '/financeiro/laboratorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  InternacoesRoute: typeof InternacoesRoute
  PequenasCirurgiasRoute: typeof PequenasCirurgiasRoute
  ProducaoHospitalarRoute: typeof ProducaoHospitalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internacoes': {
      id: '/internacoes'
      path: '/internacoes'
      fullPath: '/internacoes'
      preLoaderRoute: typeof InternacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pequenas-cirurgias': {
      id: '/pequenas-cirurgias'
      path: '/pequenas-cirurgias'
      fullPath: '/pequenas-cirurgias'
      preLoaderRoute: typeof PequenasCirurgiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao-hospitalar': {
      id: '/producao-hospitalar'
      path: '/producao-hospitalar'
      fullPath: '/producao-hospitalar'
      preLoaderRoute: typeof ProducaoHospitalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/farmacia': {
      id: '/financeiro/farmacia'
      path: '/farmacia'
      fullPath: '/financeiro/farmacia'
      preLoaderRoute: typeof FinanceiroFarmaciaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/feira': {
      id: '/financeiro/feira'
      path: '/feira'
      fullPath: '/financeiro/feira'
      preLoaderRoute: typeof FinanceiroFeiraRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/laboratorio': {
      id: '/financeiro/laboratorio'
      path: '/laboratorio'
      fullPath: '/financeiro/laboratorio'
      preLoaderRoute: typeof FinanceiroLaboratorioRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroFarmaciaRoute: typeof FinanceiroFarmaciaRoute
  FinanceiroFeiraRoute: typeof FinanceiroFeiraRoute
  FinanceiroLaboratorioRoute: typeof FinanceiroLaboratorioRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroFarmaciaRoute: FinanceiroFarmaciaRoute,
  FinanceiroFeiraRoute: FinanceiroFeiraRoute,
  FinanceiroLaboratorioRoute: FinanceiroLaboratorioRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  InternacoesRoute: InternacoesRoute,
  PequenasCirurgiasRoute: PequenasCirurgiasRoute,
  ProducaoHospitalarRoute: ProducaoHospitalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
